base:
  project: APS-project

data_source:
  h1_data: databases/secure-connect-h11.zip
  h2_data: databases/secure-connect-12.zip
  h3_data: databases/secure-connect-ap1.zip

load_data:
  data: data/raw/aps.csv

process_data:
  data: data/processed/aps.csv
final_data:
  data: data/final/aps.csv
model_dir: saved_models
reports:
  params: report/params.json
  scores: report/scores.json